language: python
python:
  - "2.7"
os: centos
install:
  - pip install -r test_requirements.txt
  - python setup.py install
script: 
  - pytest --cov 
  - COVERALLS_REPO_TOKEN=dpLeB1hkrmqFyRxfC97Q3E1xOf1OOVuxJ coveralls
virtualenv:
  system_site_packages: true
